collections:
  konzerte:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default-container"

picture:
  output: "assets/images/generated"