collections:
  konzerte:

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default-container"

picture:
  output: "assets/images/generated"

sass:
  load_paths:
    - _sass
    - vendor/bundle/ruby/3.1.0/gems/bootstrap-5.1.3/assets/stylesheets/

exclude:
  - Makefile